Repository cayleygraph/cayley, pull requests merged in 2019-09, with the labels that each got.

#832 Define and implement a new query interface
  cmd/cayley/command/repl.go
  graph/graphtest/integration.go
  internal/http/query.go
  internal/repl/repl.go
  query/gizmo/gizmo.go
  query/gizmo/gizmo_test.go
  query/graphql/graphql.go
  query/mql/mql_test.go
  query/mql/session.go
  query/session.go
  query/sexp/session.go
  server/http/api_v2.go
Labels: query languages

#834 Gizmo: Apply regex filter to lang strings as well
  graph/iterator/regex.go
Labels: bug

#840 Update configuration docs
  docs/Configuration.md
Labels: documentation

#842 Refactored Dockerfile
  Dockerfile
  configurations/default.json
  configurations/persisted.json
Labels: bug, enhancement
